package com.ufpa.scontroleportaria.model;
// Generated 22/04/2017 13:14:41 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Funcionario generated by hbm2java
 */
@Entity
@Table(name="Funcionario"
    ,catalog="SControlePortaria"
)
public class Funcionario  implements java.io.Serializable {


     private int idFuncionario;
     private Portaria portaria;
     private String nomeFuncionario;
     private String siapeFuncionario;
     private String cpfFuncionario;
     private String senhaFuncionario;
     private Date dataNascimentoFuncionario;
     private String emailFuncionario;
     private String tipoFuncionario;
     private String nomeusuario;

    public Funcionario() {
    }

    public Funcionario(int idFuncionario, Portaria portaria, String nomeFuncionario, String siapeFuncionario, String cpfFuncionario, String senhaFuncionario, Date dataNascimentoFuncionario, String emailFuncionario, String tipoFuncionario, String nomeusuario) {
       this.idFuncionario = idFuncionario;
       this.portaria = portaria;
       this.nomeFuncionario = nomeFuncionario;
       this.siapeFuncionario = siapeFuncionario;
       this.cpfFuncionario = cpfFuncionario;
       this.senhaFuncionario = senhaFuncionario;
       this.dataNascimentoFuncionario = dataNascimentoFuncionario;
       this.emailFuncionario = emailFuncionario;
       this.tipoFuncionario = tipoFuncionario;
       this.nomeusuario = nomeusuario;
    }
   
     @Id 

    
    @Column(name="idFuncionario", unique=true, nullable=false)
    public int getIdFuncionario() {
        return this.idFuncionario;
    }
    
    public void setIdFuncionario(int idFuncionario) {
        this.idFuncionario = idFuncionario;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Portaria_idPortaria", nullable=false)
    public Portaria getPortaria() {
        return this.portaria;
    }
    
    public void setPortaria(Portaria portaria) {
        this.portaria = portaria;
    }

    
    @Column(name="nomeFuncionario", nullable=false, length=45)
    public String getNomeFuncionario() {
        return this.nomeFuncionario;
    }
    
    public void setNomeFuncionario(String nomeFuncionario) {
        this.nomeFuncionario = nomeFuncionario;
    }

    
    @Column(name="siapeFuncionario", nullable=false, length=45)
    public String getSiapeFuncionario() {
        return this.siapeFuncionario;
    }
    
    public void setSiapeFuncionario(String siapeFuncionario) {
        this.siapeFuncionario = siapeFuncionario;
    }

    
    @Column(name="cpfFuncionario", nullable=false, length=45)
    public String getCpfFuncionario() {
        return this.cpfFuncionario;
    }
    
    public void setCpfFuncionario(String cpfFuncionario) {
        this.cpfFuncionario = cpfFuncionario;
    }

    
    @Column(name="senhaFuncionario", nullable=false, length=45)
    public String getSenhaFuncionario() {
        return this.senhaFuncionario;
    }
    
    public void setSenhaFuncionario(String senhaFuncionario) {
        this.senhaFuncionario = senhaFuncionario;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dataNascimentoFuncionario", nullable=false, length=10)
    public Date getDataNascimentoFuncionario() {
        return this.dataNascimentoFuncionario;
    }
    
    public void setDataNascimentoFuncionario(Date dataNascimentoFuncionario) {
        this.dataNascimentoFuncionario = dataNascimentoFuncionario;
    }

    
    @Column(name="emailFuncionario", nullable=false, length=45)
    public String getEmailFuncionario() {
        return this.emailFuncionario;
    }
    
    public void setEmailFuncionario(String emailFuncionario) {
        this.emailFuncionario = emailFuncionario;
    }

    
    @Column(name="tipoFuncionario", nullable=false, length=45)
    public String getTipoFuncionario() {
        return this.tipoFuncionario;
    }
    
    public void setTipoFuncionario(String tipoFuncionario) {
        this.tipoFuncionario = tipoFuncionario;
    }

    
    @Column(name="nomeusuario", nullable=false, length=45)
    public String getNomeusuario() {
        return this.nomeusuario;
    }
    
    public void setNomeusuario(String nomeusuario) {
        this.nomeusuario = nomeusuario;
    }




}


