package com.ufpa.scontroleportaria.model;
// Generated 23/04/2017 12:10:30 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Funcionario generated by hbm2java
 */
@Entity
@Table(name="Funcionario"
    ,catalog="SControlePortaria"
)
public class Funcionario  implements java.io.Serializable {


     private int siapeFuncionario;
     private String nomeFuncionario;
     private String cpfFuncionario;
     private String senhaFuncionario;
     private Date dataNascimentoFuncionario;
     private String emailFuncionario;
     private String tipoFuncionario;
     private Set<Portaria> portarias = new HashSet<Portaria>(0);

    public Funcionario() {
    }

	
    public Funcionario(int siapeFuncionario, String nomeFuncionario, String cpfFuncionario, String senhaFuncionario, String emailFuncionario, String tipoFuncionario) {
        this.siapeFuncionario = siapeFuncionario;
        this.nomeFuncionario = nomeFuncionario;
        this.cpfFuncionario = cpfFuncionario;
        this.senhaFuncionario = senhaFuncionario;
        this.emailFuncionario = emailFuncionario;
        this.tipoFuncionario = tipoFuncionario;
    }
    public Funcionario(int siapeFuncionario, String nomeFuncionario, String cpfFuncionario, String senhaFuncionario, Date dataNascimentoFuncionario, String emailFuncionario, String tipoFuncionario, Set<Portaria> portarias) {
       this.siapeFuncionario = siapeFuncionario;
       this.nomeFuncionario = nomeFuncionario;
       this.cpfFuncionario = cpfFuncionario;
       this.senhaFuncionario = senhaFuncionario;
       this.dataNascimentoFuncionario = dataNascimentoFuncionario;
       this.emailFuncionario = emailFuncionario;
       this.tipoFuncionario = tipoFuncionario;
       this.portarias = portarias;
    }
   
     @Id 

    
    @Column(name="siapeFuncionario", unique=true, nullable=false)
    public int getSiapeFuncionario() {
        return this.siapeFuncionario;
    }
    
    public void setSiapeFuncionario(int siapeFuncionario) {
        this.siapeFuncionario = siapeFuncionario;
    }

    
    @Column(name="nomeFuncionario", nullable=false, length=45)
    public String getNomeFuncionario() {
        return this.nomeFuncionario;
    }
    
    public void setNomeFuncionario(String nomeFuncionario) {
        this.nomeFuncionario = nomeFuncionario;
    }

    
    @Column(name="cpfFuncionario", nullable=false, length=45)
    public String getCpfFuncionario() {
        return this.cpfFuncionario;
    }
    
    public void setCpfFuncionario(String cpfFuncionario) {
        this.cpfFuncionario = cpfFuncionario;
    }

    
    @Column(name="senhaFuncionario", nullable=false, length=45)
    public String getSenhaFuncionario() {
        return this.senhaFuncionario;
    }
    
    public void setSenhaFuncionario(String senhaFuncionario) {
        this.senhaFuncionario = senhaFuncionario;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dataNascimentoFuncionario", length=10)
    public Date getDataNascimentoFuncionario() {
        return this.dataNascimentoFuncionario;
    }
    
    public void setDataNascimentoFuncionario(Date dataNascimentoFuncionario) {
        this.dataNascimentoFuncionario = dataNascimentoFuncionario;
    }

    
    @Column(name="emailFuncionario", nullable=false, length=45)
    public String getEmailFuncionario() {
        return this.emailFuncionario;
    }
    
    public void setEmailFuncionario(String emailFuncionario) {
        this.emailFuncionario = emailFuncionario;
    }

    
    @Column(name="tipoFuncionario", nullable=false, length=45)
    public String getTipoFuncionario() {
        return this.tipoFuncionario;
    }
    
    public void setTipoFuncionario(String tipoFuncionario) {
        this.tipoFuncionario = tipoFuncionario;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="funcionario")
    public Set<Portaria> getPortarias() {
        return this.portarias;
    }
    
    public void setPortarias(Set<Portaria> portarias) {
        this.portarias = portarias;
    }




}


