package com.ufpa.scontroleportaria.model;
// Generated 18/08/2017 08:59:04 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PortariaId generated by hbm2java
 */
@Embeddable
public class PortariaId  implements java.io.Serializable {


     private int pkPortaria;
     private int fkProfessor;

    public PortariaId() {
    }

    public PortariaId(int pkPortaria, int fkProfessor) {
       this.pkPortaria = pkPortaria;
       this.fkProfessor = fkProfessor;
    }
   


    @Column(name="PK_portaria", nullable=false)
    public int getPkPortaria() {
        return this.pkPortaria;
    }
    
    public void setPkPortaria(int pkPortaria) {
        this.pkPortaria = pkPortaria;
    }


    @Column(name="FK_professor", nullable=false)
    public int getFkProfessor() {
        return this.fkProfessor;
    }
    
    public void setFkProfessor(int fkProfessor) {
        this.fkProfessor = fkProfessor;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PortariaId) ) return false;
		 PortariaId castOther = ( PortariaId ) other; 
         
		 return (this.getPkPortaria()==castOther.getPkPortaria())
 && (this.getFkProfessor()==castOther.getFkProfessor());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getPkPortaria();
         result = 37 * result + this.getFkProfessor();
         return result;
   }   


}


