package com.ufpa.scontroleportaria.model;
// Generated 18/08/2017 08:59:04 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Professor generated by hbm2java
 */
@Entity
@Table(name="Professor"
    ,catalog="SControlePortaria"
)
public class Professor  implements java.io.Serializable {


     private Integer pkProfessor;
     private Funcionario funcionario;
     private Set<Portaria> portarias = new HashSet<Portaria>(0);

    public Professor() {
    }

	
    public Professor(Funcionario funcionario) {
        this.funcionario = funcionario;
    }
    public Professor(Funcionario funcionario, Set<Portaria> portarias) {
       this.funcionario = funcionario;
       this.portarias = portarias;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="PK_professor", unique=true, nullable=false)
    public Integer getPkProfessor() {
        return this.pkProfessor;
    }
    
    public void setPkProfessor(Integer pkProfessor) {
        this.pkProfessor = pkProfessor;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="FK_funcionario", nullable=false)
    public Funcionario getFuncionario() {
        return this.funcionario;
    }
    
    public void setFuncionario(Funcionario funcionario) {
        this.funcionario = funcionario;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="professor")
    public Set<Portaria> getPortarias() {
        return this.portarias;
    }
    
    public void setPortarias(Set<Portaria> portarias) {
        this.portarias = portarias;
    }




}


