package com.ufpa.scontroleportaria.model;
// Generated 26/04/2017 12:22:50 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * RelatorioF generated by hbm2java
 */
@Entity
@Table(name="RelatorioF"
    ,catalog="SControlePortaria"
)
public class RelatorioF  implements java.io.Serializable {


     private Integer pkRelatorioF;
     private String numeroDeProtocolo;
     private String pesquisaExtensao;
     private String relatorioFtituloDoProjeto;
     private String relatorioFcoordenador;
     private String memorandoDireçaoFaculdade;
     private String ataReuniao;
     private String relatorioFexecutadoFormatoProReitoria;
     private String parecerRelatorioFinal;
     private String assinaturaRespEntrega;
     private String assinaturaRescRecebimento;
     private String formacaoRecursosHumanosPesquisa;
     private String contatosNacionaisInternacionais;
     private String trabalhosPublicadosAceitos;
     private String patenteRegistroInvencao;
     private String atividadesCientificasAdministrativas;
     private String contribuicaoPensinoGraduacao;
     private String faculdadeRelatorioF;

    public RelatorioF() {
    }

	
    public RelatorioF(String numeroDeProtocolo, String pesquisaExtensao, String relatorioFtituloDoProjeto, String relatorioFcoordenador, String memorandoDireçaoFaculdade, String ataReuniao, String relatorioFexecutadoFormatoProReitoria, String parecerRelatorioFinal, String assinaturaRespEntrega, String assinaturaRescRecebimento, String formacaoRecursosHumanosPesquisa, String contatosNacionaisInternacionais, String trabalhosPublicadosAceitos, String patenteRegistroInvencao, String atividadesCientificasAdministrativas, String contribuicaoPensinoGraduacao) {
        this.numeroDeProtocolo = numeroDeProtocolo;
        this.pesquisaExtensao = pesquisaExtensao;
        this.relatorioFtituloDoProjeto = relatorioFtituloDoProjeto;
        this.relatorioFcoordenador = relatorioFcoordenador;
        this.memorandoDireçaoFaculdade = memorandoDireçaoFaculdade;
        this.ataReuniao = ataReuniao;
        this.relatorioFexecutadoFormatoProReitoria = relatorioFexecutadoFormatoProReitoria;
        this.parecerRelatorioFinal = parecerRelatorioFinal;
        this.assinaturaRespEntrega = assinaturaRespEntrega;
        this.assinaturaRescRecebimento = assinaturaRescRecebimento;
        this.formacaoRecursosHumanosPesquisa = formacaoRecursosHumanosPesquisa;
        this.contatosNacionaisInternacionais = contatosNacionaisInternacionais;
        this.trabalhosPublicadosAceitos = trabalhosPublicadosAceitos;
        this.patenteRegistroInvencao = patenteRegistroInvencao;
        this.atividadesCientificasAdministrativas = atividadesCientificasAdministrativas;
        this.contribuicaoPensinoGraduacao = contribuicaoPensinoGraduacao;
    }
    public RelatorioF(String numeroDeProtocolo, String pesquisaExtensao, String relatorioFtituloDoProjeto, String relatorioFcoordenador, String memorandoDireçaoFaculdade, String ataReuniao, String relatorioFexecutadoFormatoProReitoria, String parecerRelatorioFinal, String assinaturaRespEntrega, String assinaturaRescRecebimento, String formacaoRecursosHumanosPesquisa, String contatosNacionaisInternacionais, String trabalhosPublicadosAceitos, String patenteRegistroInvencao, String atividadesCientificasAdministrativas, String contribuicaoPensinoGraduacao, String faculdadeRelatorioF) {
       this.numeroDeProtocolo = numeroDeProtocolo;
       this.pesquisaExtensao = pesquisaExtensao;
       this.relatorioFtituloDoProjeto = relatorioFtituloDoProjeto;
       this.relatorioFcoordenador = relatorioFcoordenador;
       this.memorandoDireçaoFaculdade = memorandoDireçaoFaculdade;
       this.ataReuniao = ataReuniao;
       this.relatorioFexecutadoFormatoProReitoria = relatorioFexecutadoFormatoProReitoria;
       this.parecerRelatorioFinal = parecerRelatorioFinal;
       this.assinaturaRespEntrega = assinaturaRespEntrega;
       this.assinaturaRescRecebimento = assinaturaRescRecebimento;
       this.formacaoRecursosHumanosPesquisa = formacaoRecursosHumanosPesquisa;
       this.contatosNacionaisInternacionais = contatosNacionaisInternacionais;
       this.trabalhosPublicadosAceitos = trabalhosPublicadosAceitos;
       this.patenteRegistroInvencao = patenteRegistroInvencao;
       this.atividadesCientificasAdministrativas = atividadesCientificasAdministrativas;
       this.contribuicaoPensinoGraduacao = contribuicaoPensinoGraduacao;
       this.faculdadeRelatorioF = faculdadeRelatorioF;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="PK_relatorioF", unique=true, nullable=false)
    public Integer getPkRelatorioF() {
        return this.pkRelatorioF;
    }
    
    public void setPkRelatorioF(Integer pkRelatorioF) {
        this.pkRelatorioF = pkRelatorioF;
    }

    
    @Column(name="numeroDeProtocolo", nullable=false, length=45)
    public String getNumeroDeProtocolo() {
        return this.numeroDeProtocolo;
    }
    
    public void setNumeroDeProtocolo(String numeroDeProtocolo) {
        this.numeroDeProtocolo = numeroDeProtocolo;
    }

    
    @Column(name="pesquisaExtensao", nullable=false, length=45)
    public String getPesquisaExtensao() {
        return this.pesquisaExtensao;
    }
    
    public void setPesquisaExtensao(String pesquisaExtensao) {
        this.pesquisaExtensao = pesquisaExtensao;
    }

    
    @Column(name="relatorioFTituloDoProjeto", nullable=false, length=45)
    public String getRelatorioFtituloDoProjeto() {
        return this.relatorioFtituloDoProjeto;
    }
    
    public void setRelatorioFtituloDoProjeto(String relatorioFtituloDoProjeto) {
        this.relatorioFtituloDoProjeto = relatorioFtituloDoProjeto;
    }

    
    @Column(name="relatorioFCoordenador", nullable=false, length=45)
    public String getRelatorioFcoordenador() {
        return this.relatorioFcoordenador;
    }
    
    public void setRelatorioFcoordenador(String relatorioFcoordenador) {
        this.relatorioFcoordenador = relatorioFcoordenador;
    }

    
    @Column(name="memorandoDireçaoFaculdade", nullable=false, length=45)
    public String getMemorandoDireçaoFaculdade() {
        return this.memorandoDireçaoFaculdade;
    }
    
    public void setMemorandoDireçaoFaculdade(String memorandoDireçaoFaculdade) {
        this.memorandoDireçaoFaculdade = memorandoDireçaoFaculdade;
    }

    
    @Column(name="ataReuniao", nullable=false, length=45)
    public String getAtaReuniao() {
        return this.ataReuniao;
    }
    
    public void setAtaReuniao(String ataReuniao) {
        this.ataReuniao = ataReuniao;
    }

    
    @Column(name="relatorioFExecutadoFormatoProReitoria", nullable=false, length=45)
    public String getRelatorioFexecutadoFormatoProReitoria() {
        return this.relatorioFexecutadoFormatoProReitoria;
    }
    
    public void setRelatorioFexecutadoFormatoProReitoria(String relatorioFexecutadoFormatoProReitoria) {
        this.relatorioFexecutadoFormatoProReitoria = relatorioFexecutadoFormatoProReitoria;
    }

    
    @Column(name="parecerRelatorioFinal", nullable=false, length=45)
    public String getParecerRelatorioFinal() {
        return this.parecerRelatorioFinal;
    }
    
    public void setParecerRelatorioFinal(String parecerRelatorioFinal) {
        this.parecerRelatorioFinal = parecerRelatorioFinal;
    }

    
    @Column(name="assinaturaRespEntrega", nullable=false, length=45)
    public String getAssinaturaRespEntrega() {
        return this.assinaturaRespEntrega;
    }
    
    public void setAssinaturaRespEntrega(String assinaturaRespEntrega) {
        this.assinaturaRespEntrega = assinaturaRespEntrega;
    }

    
    @Column(name="assinaturaRescRecebimento", nullable=false, length=45)
    public String getAssinaturaRescRecebimento() {
        return this.assinaturaRescRecebimento;
    }
    
    public void setAssinaturaRescRecebimento(String assinaturaRescRecebimento) {
        this.assinaturaRescRecebimento = assinaturaRescRecebimento;
    }

    
    @Column(name="formacaoRecursosHumanosPesquisa", nullable=false, length=45)
    public String getFormacaoRecursosHumanosPesquisa() {
        return this.formacaoRecursosHumanosPesquisa;
    }
    
    public void setFormacaoRecursosHumanosPesquisa(String formacaoRecursosHumanosPesquisa) {
        this.formacaoRecursosHumanosPesquisa = formacaoRecursosHumanosPesquisa;
    }

    
    @Column(name="contatosNacionaisInternacionais", nullable=false, length=45)
    public String getContatosNacionaisInternacionais() {
        return this.contatosNacionaisInternacionais;
    }
    
    public void setContatosNacionaisInternacionais(String contatosNacionaisInternacionais) {
        this.contatosNacionaisInternacionais = contatosNacionaisInternacionais;
    }

    
    @Column(name="trabalhosPublicadosAceitos", nullable=false, length=45)
    public String getTrabalhosPublicadosAceitos() {
        return this.trabalhosPublicadosAceitos;
    }
    
    public void setTrabalhosPublicadosAceitos(String trabalhosPublicadosAceitos) {
        this.trabalhosPublicadosAceitos = trabalhosPublicadosAceitos;
    }

    
    @Column(name="patenteRegistroInvencao", nullable=false, length=45)
    public String getPatenteRegistroInvencao() {
        return this.patenteRegistroInvencao;
    }
    
    public void setPatenteRegistroInvencao(String patenteRegistroInvencao) {
        this.patenteRegistroInvencao = patenteRegistroInvencao;
    }

    
    @Column(name="atividadesCientificasAdministrativas", nullable=false, length=45)
    public String getAtividadesCientificasAdministrativas() {
        return this.atividadesCientificasAdministrativas;
    }
    
    public void setAtividadesCientificasAdministrativas(String atividadesCientificasAdministrativas) {
        this.atividadesCientificasAdministrativas = atividadesCientificasAdministrativas;
    }

    
    @Column(name="contribuicaoPEnsinoGraduacao", nullable=false, length=45)
    public String getContribuicaoPensinoGraduacao() {
        return this.contribuicaoPensinoGraduacao;
    }
    
    public void setContribuicaoPensinoGraduacao(String contribuicaoPensinoGraduacao) {
        this.contribuicaoPensinoGraduacao = contribuicaoPensinoGraduacao;
    }

    
    @Column(name="faculdadeRelatorioF", length=45)
    public String getFaculdadeRelatorioF() {
        return this.faculdadeRelatorioF;
    }
    
    public void setFaculdadeRelatorioF(String faculdadeRelatorioF) {
        this.faculdadeRelatorioF = faculdadeRelatorioF;
    }




}


