package com.ufpa.scontroleportaria.model;
// Generated 22/04/2017 13:14:41 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Relatorio generated by hbm2java
 */
@Entity
@Table(name="Relatorio"
    ,catalog="SControlePortaria"
)
public class Relatorio  implements java.io.Serializable {


     private int idRelatorio;
     private Portaria portaria;
     private Date relatorioDataCriacao;
     private String qtdPortariasCadastradas;
     private String nomesProfessoresCoordenadores;
     private String qtdPortariasVigentes;
     private String qtdPortariasExpiradas;

    public Relatorio() {
    }

    public Relatorio(int idRelatorio, Portaria portaria, Date relatorioDataCriacao, String qtdPortariasCadastradas, String nomesProfessoresCoordenadores, String qtdPortariasVigentes, String qtdPortariasExpiradas) {
       this.idRelatorio = idRelatorio;
       this.portaria = portaria;
       this.relatorioDataCriacao = relatorioDataCriacao;
       this.qtdPortariasCadastradas = qtdPortariasCadastradas;
       this.nomesProfessoresCoordenadores = nomesProfessoresCoordenadores;
       this.qtdPortariasVigentes = qtdPortariasVigentes;
       this.qtdPortariasExpiradas = qtdPortariasExpiradas;
    }
   
     @Id 

    
    @Column(name="idRelatorio", unique=true, nullable=false)
    public int getIdRelatorio() {
        return this.idRelatorio;
    }
    
    public void setIdRelatorio(int idRelatorio) {
        this.idRelatorio = idRelatorio;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Portaria_idPortaria", nullable=false)
    public Portaria getPortaria() {
        return this.portaria;
    }
    
    public void setPortaria(Portaria portaria) {
        this.portaria = portaria;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="relatorioDataCriacao", nullable=false, length=10)
    public Date getRelatorioDataCriacao() {
        return this.relatorioDataCriacao;
    }
    
    public void setRelatorioDataCriacao(Date relatorioDataCriacao) {
        this.relatorioDataCriacao = relatorioDataCriacao;
    }

    
    @Column(name="qtdPortariasCadastradas", nullable=false, length=45)
    public String getQtdPortariasCadastradas() {
        return this.qtdPortariasCadastradas;
    }
    
    public void setQtdPortariasCadastradas(String qtdPortariasCadastradas) {
        this.qtdPortariasCadastradas = qtdPortariasCadastradas;
    }

    
    @Column(name="nomesProfessoresCoordenadores", nullable=false, length=45)
    public String getNomesProfessoresCoordenadores() {
        return this.nomesProfessoresCoordenadores;
    }
    
    public void setNomesProfessoresCoordenadores(String nomesProfessoresCoordenadores) {
        this.nomesProfessoresCoordenadores = nomesProfessoresCoordenadores;
    }

    
    @Column(name="qtdPortariasVigentes", nullable=false, length=45)
    public String getQtdPortariasVigentes() {
        return this.qtdPortariasVigentes;
    }
    
    public void setQtdPortariasVigentes(String qtdPortariasVigentes) {
        this.qtdPortariasVigentes = qtdPortariasVigentes;
    }

    
    @Column(name="qtdPortariasExpiradas", nullable=false, length=45)
    public String getQtdPortariasExpiradas() {
        return this.qtdPortariasExpiradas;
    }
    
    public void setQtdPortariasExpiradas(String qtdPortariasExpiradas) {
        this.qtdPortariasExpiradas = qtdPortariasExpiradas;
    }




}


